# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gr.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1921, 1051))
        self.label.setStyleSheet("beckground-image: url(:/background/fon.png);\n"
"background-image: url(:/background/fon.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(419, 333, 1081, 138))
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("/* Rectangle 7 */\n"
"\n"
"position: absolute;\n"
"width: 1081px;\n"
"height: 138px;\n"
"left: 419px;\n"
"top: 333px;\n"
"\n"
"background: linear-gradient(90deg, rgba(238, 240, 252, 0) 0%, rgba(255, 255, 255, 0.2) 50%, rgba(238, 240, 252, 0) 100%), #E8CAEC;\n"
"box-shadow: 0px 4px 3.8px rgba(0, 0, 0, 0.25);\n"
"border-radius: 28px;\n"
"\n"
"\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(419, 518, 1081, 138))
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(28)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("/* Rectangle 7 */\n"
"\n"
"position: absolute;\n"
"width: 1081px;\n"
"height: 138px;\n"
"left: 419px;\n"
"top: 333px;\n"
"\n"
"background: linear-gradient(90deg, rgba(238, 240, 252, 0) 0%, rgba(255, 255, 255, 0.2) 50%, rgba(238, 240, 252, 0) 100%), #E8CAEC;\n"
"box-shadow: 0px 4px 3.8px rgba(0, 0, 0, 0.25);\n"
"border-radius: 28px;\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(635, 703, 650, 83))
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(20)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("/* Rectangle 9 */\n"
"\n"
"position: absolute;\n"
"width: 650px;\n"
"height: 83px;\n"
"left: 635px;\n"
"top: 703px;\n"
"\n"
"background: linear-gradient(90deg, rgba(238, 240, 252, 0) 0%, rgba(255, 255, 255, 0.2) 50%, rgba(238, 240, 252, 0) 100%), #E8CAEC;\n"
"box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 28px;\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(635, 833, 650, 83))
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(20)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("/* Rectangle 9 */\n"
"\n"
"position: absolute;\n"
"width: 650px;\n"
"height: 83px;\n"
"left: 635px;\n"
"top: 703px;\n"
"\n"
"background: linear-gradient(90deg, rgba(238, 240, 252, 0) 0%, rgba(255, 255, 255, 0.2) 50%, rgba(238, 240, 252, 0) 100%), #E8CAEC;\n"
"box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 28px;\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "G-Lune"))
        self.pushButton.setText(_translate("MainWindow", "Генерация гороскопа"))
        self.pushButton_2.setText(_translate("MainWindow", "Проверка совместимости"))
        self.pushButton_3.setText(_translate("MainWindow", "Все пользователи"))
        self.pushButton_4.setText(_translate("MainWindow", "Все совместимости"))
import goroskop_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
