# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gr2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 80, 1661, 291))
        self.label.setStyleSheet("background-image: url(:/newPrefix/Downloads/G-lune.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(151, 375, 601, 44))
        self.lineEdit.setStyleSheet("/* Rectangle 10 */\n"
"\n"
"position: absolute;\n"
"width: 601px;\n"
"height: 44px;\n"
"left: 151px;\n"
"top: 375px;\n"
"\n"
"background: linear-gradient(90deg, rgba(238, 240, 252, 0) 0%, rgba(255, 255, 255, 0.2) 50%, rgba(238, 240, 252, 0) 100%), #DFDFDF;\n"
"box-shadow: 0px 4px 3.8px rgba(0, 0, 0, 0.25);\n"
"border-radius: 28px;\n"
"transform: matrix(1, 0, 0, -1, 0, 0);\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(151, 464, 601, 44))
        self.lineEdit_2.setStyleSheet("/* Rectangle 10 */\n"
"\n"
"position: absolute;\n"
"width: 601px;\n"
"height: 44px;\n"
"left: 151px;\n"
"top: 375px;\n"
"\n"
"background: linear-gradient(90deg, rgba(238, 240, 252, 0) 0%, rgba(255, 255, 255, 0.2) 50%, rgba(238, 240, 252, 0) 100%), #DFDFDF;\n"
"box-shadow: 0px 4px 3.8px rgba(0, 0, 0, 0.25);\n"
"border-radius: 28px;\n"
"transform: matrix(1, 0, 0, -1, 0, 0);\n"
"")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(151, 730, 601, 44))
        self.lineEdit_3.setStyleSheet("/* Rectangle 14 */\n"
"\n"
"position: absolute;\n"
"width: 601px;\n"
"height: 44px;\n"
"left: 151px;\n"
"top: 730px;\n"
"\n"
"background: linear-gradient(90deg, rgba(238, 240, 252, 0) 0%, rgba(255, 255, 255, 0.2) 50%, rgba(238, 240, 252, 0) 100%), #E2E2E2;\n"
"box-shadow: 0px 4px 3.8px rgba(0, 0, 0, 0.25);\n"
"border-radius: 28px;\n"
"transform: matrix(1, 0, 0, -1, 0, 0);\n"
"")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(229, 546, 446, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("/* Rectangle 12 */\n"
"\n"
"position: absolute;\n"
"width: 446px;\n"
"height: 51px;\n"
"left: 229px;\n"
"top: 546px;\n"
"\n"
"background: linear-gradient(90deg, rgba(238, 240, 252, 0) 0%, rgba(255, 255, 255, 0.2) 50%, rgba(238, 240, 252, 0) 100%), #E8CAEC;\n"
"box-shadow: 0px 4px 3.8px rgba(0, 0, 0, 0.25);\n"
"border-radius: 20px;\n"
"transform: matrix(1, 0, 0, -1, 0, 0);\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(229, 802, 446, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("/* Rectangle 18 */\n"
"\n"
"position: absolute;\n"
"width: 446px;\n"
"height: 51px;\n"
"left: 229px;\n"
"top: 802px;\n"
"\n"
"background: linear-gradient(90deg, rgba(238, 240, 252, 0) 0%, rgba(255, 255, 255, 0.2) 50%, rgba(238, 240, 252, 0) 100%), #E8CAEC;\n"
"box-shadow: 0px 4px 3.8px rgba(0, 0, 0, 0.25);\n"
"border-radius: 20px;\n"
"transform: matrix(1, 0, 0, -1, 0, 0);\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(229, 920, 446, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("/* Rectangle 20 */\n"
"\n"
"position: absolute;\n"
"width: 446px;\n"
"height: 51px;\n"
"left: 229px;\n"
"top: 962px;\n"
"\n"
"background: linear-gradient(90deg, rgba(238, 240, 252, 0) 0%, rgba(255, 255, 255, 0.2) 50%, rgba(238, 240, 252, 0) 100%), #E8CAEC;\n"
"box-shadow: 0px 4px 3.8px rgba(0, 0, 0, 0.25);\n"
"border-radius: 20px;\n"
"transform: matrix(1, 0, 0, -1, 0, 0);\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 280, 538, 65))
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(151, 345, 55, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(151, 430, 444, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(151, 620, 538, 65))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(151, 690, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(1240, 280, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(1260, 920, 446, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("/* Rectangle 22 */\n"
"\n"
"position: absolute;\n"
"width: 446px;\n"
"height: 51px;\n"
"left: 1259px;\n"
"top: 962px;\n"
"\n"
"background: linear-gradient(90deg, rgba(238, 240, 252, 0) 0%, rgba(255, 255, 255, 0.2) 50%, rgba(238, 240, 252, 0) 100%), #E8CAEC;\n"
"box-shadow: 0px 4px 3.8px rgba(0, 0, 0, 0.25);\n"
"border-radius: 20px;\n"
"transform: matrix(1, 0, 0, -1, 0, 0);\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(1310, 390, 344, 458))
        self.widget.setStyleSheet("/* image 13 */\n"
"\n"
"position: absolute;\n"
"width: 344px;\n"
"height: 458px;\n"
"left: 1310px;\n"
"top: 327px;\n"
"\n"
"background: linear-gradient(0deg, #E8CAEC, #E8CAEC), url(image.png);\n"
"border-radius: 25px;\n"
"")
        self.widget.setObjectName("widget")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(1440, 290, 401, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "G-Lune"))
        self.pushButton.setText(_translate("MainWindow", "Сгенерировать гороскоп "))
        self.pushButton_2.setText(_translate("MainWindow", "Загрузить данные "))
        self.pushButton_3.setText(_translate("MainWindow", "Изменить данные "))
        self.label_2.setText(_translate("MainWindow", "Генерация гороскопа "))
        self.label_3.setText(_translate("MainWindow", "Имя:"))
        self.label_4.setText(_translate("MainWindow", "Дата рождения: (ДД.ММ.ГГГГ)"))
        self.label_5.setText(_translate("MainWindow", "Найти пользователя "))
        self.label_6.setText(_translate("MainWindow", "Введите имя:"))
        self.label_7.setText(_translate("MainWindow", "Гороскоп:"))
        self.pushButton_4.setText(_translate("MainWindow", "Узнать больше"))
import goroskop_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
